rpm_profiles:
  fc33-standalone-gcc:
    installs_from: [ image, local_repo = fc33 ]
    image: fedora-with-rpm
    options: &1
      - "--define=_build x86_64-redhat-linux-gnu"
      - "--define=_host x86_64-redhat-linux-gnu"
      - "--define=_target x86_64-pc-linux-gnu"
      - "--define=_fedora_dependencies 1"
      - "--define=dist .fc33"
      - --without
      - threads
      - --with
      - standalone
    native_options: *1
    additional_podman_args: [ "--volume", "/tmp/dnfcache:/var/cache/dnf" ]
    dist: fc33
  fc33:
    installs_from: [ image, local_repo = fc33 ]
    image: fedora-with-rpm
    options: &1
      - "--define=_build x86_64-redhat-linux-gnu"
      - "--define=_host x86_64-redhat-linux-gnu"
      - "--define=_target x86_64-pc-linux-gnu"
      - "--define=_fedora_dependencies 1"
      - "--define=dist .fc33"
    native_options: *1
    #native_options: ["--define=_build x86_64-redhat-linux-gnu", "--define=_host x86_64-redhat-linux-gnu", "--define=_target x86_64-redhat-linux-gnu",  "--define=_fedora_dependencies 1", "--define=dist .fc33"]
    additional_podman_args: [ "--volume", "/tmp/dnfcache:/var/cache/dnf" ]
  digi1:
    installs_from: [ image, local_repo = fc33 ]
    image: fedora-with-rpm
    options: ["--define=_build x86_64-redhat-linux-gnu", "--define=_host x86_64-pc-linux-gnu", "--define=_target x86_64-pc-linux-gnu", "--define=dist .digi1"]
    native_options: ["--define=_build x86_64-pc-linux-gnu", "--define=_host x86_64-pc-linux-gnu", "--define=_target x86_64-pc-linux-gnu", "--define=dist .digi1"]
    additional_podman_args: [ "--volume", "/tmp/dnfcache:/var/cache/dnf" ]
  digi2:
    installs_from: [ local_repo = digi1 ]
    image: digitalis-stage1
    options: &1 ["--define=_build x86_64-pc-linux-gnu", "--define=_host x86_64-pc-linux-gnu", "--define=_target x86_64-pc-linux-gnu", "--define=dist .digi2"]
    native_options: *1
rpm_option_sets:
  fc33-standalone-gcc:
    image: fedora-with-rpm
    options: 
      - "--define=_build x86_64-redhat-linux-gnu"
      - "--define=_host x86_64-redhat-linux-gnu"
      - "--define=_target x86_64-pc-linux-gnu"
      - "--define=_fedora_dependencies 1"
      - "--define=dist .fc33"
      - --without
      - threads
      - --with
      - standalone
  fc33:
    image: fedora-with-rpm
    options:
      - "--define=_build x86_64-redhat-linux-gnu"
      - "--define=_host x86_64-redhat-linux-gnu"
      - "--define=_target x86_64-pc-linux-gnu"
      - "--define=_fedora_dependencies 1"
      - "--define=dist .fc33"
  digi1: 
    image: fedora-with-rpm
    options: ["--define=_build x86_64-redhat-linux-gnu", "--define=_host x86_64-pc-linux-gnu", "--define=_target x86_64-pc-linux-gnu", "--define=dist .digi1"]
build_images:
  fedora-with-rpm:
    script: |
        ctr=$(buildah from fedora:33)

        mkdir -p /tmp/dnfcache
        buildah run --net host "$ctr" sh -c 'echo "keepcache=True" >>/etc/dnf/dnf.conf'
        buildah run --net host --volume /tmp/dnfcache:/var/cache/dnf "$ctr" dnf install -y rpm-build createrepo_c
        buildah run --net host "$ctr" sh -c 'echo "%_topdir /rpmbuild" >>~/.rpmmacros'
        buildah run --net host "$ctr" sh -c 'echo "%_unique_build_ids 1" >>~/.rpmmacros'
        # work around toolchain magic in Fedora 33 setting $CC to random crud
        buildah run --net host "$ctr" sh -c 'sed -i "/  CC=/d" /lib/rpm/redhat/macros'
        buildah run --net host "$ctr" sh -c 'sed -i "/  CXX=/c\\  true" /lib/rpm/redhat/macros'
        buildah run --net host "$ctr" sh -c 'cat >/etc/yum.repos.d/local-bootstrap.repo' <<EOF
        [local-bootstrap]
        name=local-bootstrap
        baseurl=/repo
        enabled=1
        metadata_expire=1s
        gpgcheck=0
        EOF
        buildah commit "$ctr" fedora-with-rpm
    dirs: [ "/tmp/dnfcache" ]
    additional_podman_args: [ "--volume", "/tmp/dnfcache:/var/cache/dnf" ]
    has_axioms: true
    profile: fc33
    install_packages: []
    repository: local-bootstrap
  digitalis-stage1:
    # TODO this suffers from bad
    script: |
        mkdir -p /tmp/repo_digi1
        find ../rpmbuild/RPMS -name '*.'digi1'.*' -exec cp {} /tmp/repo_digi1 ';'
        ctr=$(buildah from fedora-with-rpm)
        VOLUMES="--volume /tmp/dnfcache:/var/cache/dnf --volume /tmp/repo_digi1:/repo"
        podman run --net host $VOLUMES --rm fedora-with-rpm createrepo_c /repo
        buildah run --net host $VOLUMES "$ctr" -- mkdir /new_root
        buildah run --net host $VOLUMES "$ctr" -- dnf install -y \
            --verbose --repo=local-bootstrap --installroot=/new_root --releasever=digi1 \
            fs-tree
        buildah run --net host $VOLUMES "$ctr" -- dnf install -y \
            --verbose --repo=local-bootstrap --installroot=/new_root --releasever=digi1 \
            digitalis-bootstrap-repository base-system

        rm -rf /tmp/$ctr-new_root

        buildah unshare sh -c 'cp -rp $(buildah mount '$ctr')/new_root /tmp/'$ctr'-new_root'
        buildah umount "$ctr"
        buildah rm "$ctr"

        ctr1=$(buildah from scratch)

        buildah copy "$ctr1" /tmp/"$ctr"-new_root /
        buildah run --net host --volume /tmp/repo_digi1:/repo "$ctr1" -- dnf install -y --releasever=digi1 \
            fs-tree digitalis-bootstrap-repository base-system createrepo_c
        buildah run --net host "$ctr1" sh -c 'echo "%_topdir /rpmbuild" >>~/.rpmmacros'
        buildah commit "$ctr1" digitalis-stage1
        buildah rm "$ctr1"
    installs_from: digi1
    install_packages:
      - fs-tree
      - digitalis-bootstrap-repository
      - base-system
      - createrepo_c
      - dnf
    profile: digi1
    repository: digitalis
  digitalis-stage2:
    # TODO this suffers from bad
    script: |
        mkdir -p /tmp/repo_digi2
        find ../rpmbuild/RPMS -name '*.'digi2'.*' -exec cp {} /tmp/repo_digi2 ';'
        ctr=$(buildah from digitalis-stage1)
        VOLUMES="--volume /tmp/dnfcache:/var/cache/dnf --volume /tmp/repo_digi2:/repo"
        podman run --net host $VOLUMES --rm digitalis-stage1 createrepo_c /repo
        buildah run --net host $VOLUMES "$ctr" -- rm -rf /new_root
        buildah run --net host $VOLUMES "$ctr" -- mkdir /new_root
        buildah run --net host $VOLUMES "$ctr" -- dnf install -y \
            --verbose --repo=digitalis --installroot=/new_root --releasever=digi2 \
            fs-tree
        buildah run --net host $VOLUMES "$ctr" -- dnf install -y \
            --verbose --repo=digitalis --installroot=/new_root --releasever=digi2 \
            digitalis-bootstrap-repository base-system

        chmod -R 755 /tmp/$ctr-new_root/new_root/etc/ssl/certs
        rm -rf /tmp/$ctr-new_root

        buildah unshare sh -c 'cp -rp $(buildah mount '$ctr')/new_root /tmp/'$ctr'-new_root'
        buildah umount "$ctr"
        buildah rm "$ctr"

        ctr1=$(buildah from scratch)

        buildah copy "$ctr1" /tmp/"$ctr"-new_root /
        buildah run --net host --volume /tmp/repo_digi2:/repo "$ctr1" -- dnf install -y --releasever=digi1 \
            fs-tree digitalis-bootstrap-repository base-system createrepo_c
        buildah run --net host "$ctr1" sh -c 'echo "%_topdir /rpmbuild" >>~/.rpmmacros'
        buildah commit "$ctr1" digitalis-stage2
        buildah rm "$ctr1"
    installs_from: digi2
    install_packages:
      - fs-tree
      - digitalis-bootstrap-repository
      - base-system
      - createrepo_c
      - dnf
    profile: digi2
    repository: digitalis
default_image: digitalis-stage2
